### ISSUE TITLE
Zombie code 🤢🤢🤢

### ISSUE THREAD

**Issue by thegoldgoat** [fabifont/abb-bot#2]
https://github.com/fabifont/abb-bot/blob/413bc7bc37a47b221cd9133bf11049b7ba8af94e/src/main/java/com/fabifont/aliexpress/account/AccountWorker.java#L105

Remove ASAP please 😅😀🤯😎

Don’t know if there’s any more zombie code elsewhere, further investigation needed 🕵🏻‍♂️

**Comment by Rubenxx00** [comment]
![tru](https://user-images.githubusercontent.com/38732550/102831921-43477a00-43ed-11eb-8f16-e657a4b9b71c.jpeg)

**Comment by thegoldgoat** [comment]
Solved by 99613ac1a40fc73d23d7a0cd5a1e74e5edf231c8

@Rubenxx00 always link commits before closing issues 😉
