### ISSUE TITLE
Non capisco come continuare

### ISSUE THREAD

**Issue by unusualvalve** [fabifont/abb-bot#6]
Una volta che estraggo la cartella aliexpress dal rar, non capisco come far avviare il programma. Il JDK mi risulta completamente inutile, non capisco dove mettere il link visto che "config.properties" non esiste

**Comment by fabifont** [comment]
> Una volta che estraggo la cartella aliexpress dal rar, non capisco come far avviare il programma. Il JDK mi risulta completamente inutile, non capisco dove mettere il link visto che "config.properties" non esiste

Basta seguire il README.md, serve comunque qualche base di programmazione
