### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Ananas0631** [fabifont/abb-bot#7]
"Avvia una volta l'applicazione per generare i file di default che si trovano nella cartella C:\\Users<Utente>\\aliexpress per windows e /home/aliexpress per Linux"
Hi,

What application is that? Which one?

**Comment by fabifont** [comment]
@Ananas0631 Please read all the README.md before opening issues.

**Comment by Ananas0631** [comment]
I read it bro,Its a part from readme.md

**Comment by Ananas0631** [comment]
Im working on it nearly 4 hours

**Comment by fabifont** [comment]
@Ananas0631 There are two ways to run the application: Run with intelliJ and Run with Maven, both explained in the README.md

**Comment by Ananas0631** [comment]
Yeah,it writes on readme.md  but I dont know what do you mean by "the application",the application we created?

**Comment by fabifont** [comment]
@Ananas0631 Man, the application is the bot, the program...
